SELECT 
		EMP_ID,
		EMP_NAME,
		SALARY
		
FROM EMPLOYEE
WHERE SALARY > 4000000;

SELECT
FROM EMPLOYEE
WHERE SALARY BETWEEN 입력최소 
ORDER BY SALARY DESC;


SELECT
	EMP_ID,
	EMP_NAME,
	DEPT_TITLE,
	JOB_NAME;
	
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '없음') DEPT_TITLE, JOB_NAME 
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE DEPT_TITLE = '인사관리부'
ORDER BY DEPT_ID ASC;


-- TB_USER 테이블 생성
CREATE TABLE TB_USER(
		USER_NO 		NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
		USER_ID 		VARCHAR2(30) NOT NULL,
		USER_PW 		VARCHAR2(30) NOT NULL,
		USER_NAME 	VARCHAR2(30) NOT NULL,
		ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_USER.USER_NO 		IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID 		IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW 		IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME 	IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';


-- USER_NO 컬럼에 삽입 될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT 
INSERT INTO TB_USER
VALUES(SEQ_USER_NO.NEXTVAL, 
		'user01', 'pass01', '유저일', DEFAULT);

SELECT * FROM TB_USER;

COMMIT;

UPDATE TB_USER
SET		USER_NAME = '홍길동'
WHERE
		USER_ID = 'user01'
AND USER_PW = 'pass01';
-- 아이디 비밀번호 일치 -> 수정 성공 (1)
-- 아이디 또는 비밀번호 불일치 -> 수정 실패(0)
	
ROLLBACK;

SELECT
		EMP_ID,
		EMP_NAME,
		
		SALARY,
		DEPT_TITLE
		
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE SUBSTR(EMP_NO,8,1) = '2' AS "GENDER"
	AND SALARY BETWEEN 3000000 AND 4000000
ORDER BY SALARY DESC;

SELECT
      EMP_ID 사번,
      EMP_NAME 이름,
      DECODE(SUBSTR(EMP_NO,8,2),1,'M',2,'F') AS "성별",
      SALARY 급여,
      JOB_NAME 직급명,
      NVL(DEPT_TITLE, '없음') DEPT_TITLE
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);



SELECT*FROM TB_USER;

-- 모든 USER 조회
SELECT
	USER_NO,
	USER_ID,
	USER_PW,
	USER_NAME,
	
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM TB_USER
ORDER BY USER_NO ASC;


-- 검색어가 이름에 포함된 User 조회
SELECT
	USER_NO,
	USER_ID,
	USER_PW,
	USER_NAME,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') 
		ENROLL_DATE
FROM TB_USER
WHERE USER_NAME LIKE '%' || ? || '%'
ORDER BY USER_NO ASC;


-- USER_NO를 입력 받아 일치하는 USER 삭제
DELETE
FROM TB_USER
WHERE USER_NO = 8;
-- 일치하는 USER_NO가 있을 경우 : 1행 삭제
-- 일치하는 USER_NO가 없을 경우 : 0행 삭제

ROLLBACK;

-- ID, PW 가 일치하는 회원의 USER_NO 조회
SELECT USER_NO
FROM TB_USER
WHERE USER_ID = 'user04'
	AND USER_PW = 'pass04';


-- ID, PW가 일치하는 회원이 있을 경우 이름 수정(UPDATE)
UPDATE TB_USER
SET 
	USER_NAME = ?
WHERE 
		USER_NO;

-- 중복되는 아이디가 있는지 조회
-- 중복이면 1, 아니면 0
SELECT COUNT(*)
FROM TB_USER
WHERE USER_ID = 'user04';

SELECT*FROM TB_USER
ORDER BY 1 ASC;

COMMIT;

DELETE
FROM TB_USER;

SELECT *
FROM TB_USER
WHERE USER_NO = TO_NUMBER('20');

