-- 문제 1
SELECT 
		STUDENT_NAME 학생이름,
		STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

-- 문제 2
SELECT 
		STUDENT_NAME,
		STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 문제 3
SELECT
    STUDENT_NAME AS "학생이름",
    STUDENT_NO AS "학번",
    STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경%' OR STUDENT_ADDRESS LIKE '강%')
  AND STUDENT_NO LIKE '9%'
ORDER BY STUDENT_NAME ASC;


-- 4번
SELECT 
		PROFESSOR_NAME,
		PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN ASC;


-- 5번
SELECT
		STUDENT_NO,
		TO_CHAR(POINT, 'FM9.00') 학점
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
	AND TERM_NO = '200402'
ORDER BY POINT DESC, STUDENT_NO ASC;

-- 6번 
SELECT
		STUDENT_NO,
		STUDENT_NAME,
		DEPARTMENT_NAME
		
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;


-- 7번
SELECT 
		CLASS_NAME,
		DEPARTMENT_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO);

-- 8번
SELECT 
		CLASS_NAME,
		PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING (DEPARTMENT_NO);


-- 9번
SELECT 
		CLASS_NAME,
		PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY CLASS_NAME ASC;


-- 10번
SELECT 
    STUDENT_NO AS "학번",
    STUDENT_NAME AS "학생이름",
    ROUND(AVG(POINT), 1) AS "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));


-- 11번
SELECT
		DEPARTMENT_NAME AS "과목 이름",
		STUDENT_NAME AS "학생이름",
		PROFESSOR_NAME AS "지도교수 이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON
	(TB_STUDENT.COACH_PROFESSOR_NO = TB_PROFESSOR.PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';


-- 12번

SELECT 
		STUDENT_NAME,
		TERM_NO AS "TERM_NAME"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE TERM_NO LIKE '2007%'
	AND CLASS_NO = 'C2604100';

-- 13번

SELECT
	CLASS_NAME,
	DEPARTMENT_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR
WHERE CATEGORY = '예체능'
	AND DEPARTMENT_NO = (
			SELECT
			FROM 
			)
;


-- 14번
SELECT
		STUDENT_NAME,
		NVL (PROFESSOR_NAME, '지도교수 미지정')
FROM TB_STUDENT
JOIN TB_DEPARTMENT   USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO  ASC;

-- 15번
SELECT
		STUDENT_NO "학번",
		STUDENT_NAME "이름",
		DEPARTMENT_NAME "학과 이름",
		POINT "평점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN != 'Y'
	AND POINT >= '4.0';





-- 18번
SELECT 
		STUDENT_NO,
		STUDENT_NAME
FROM TB_STUDENT
WHERE ;