-- 문제 1
SELECT 
		STUDENT_NAME 학생이름,
		STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

-- 문제 2
SELECT 
		STUDENT_NAME,
		STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 문제 3
SELECT
		STUDENT_NAME "학생이름",
		STUDENT_NO "학번",
		STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '경%'
   OR STUDENT_ADDRESS LIKE '강%'
AND STUDENT_NO LIKE '9%'
ORDER BY STUDENT_NAME ASC;




-- 4번
